Sakomws build l2ami engops
OpenGov/amazon-eks-ami pull request #2
Opened 2019-06-18 01:54 UTC by sakomws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2019-06-18 04:58 UTC, Chili-Man requested changes

2019-06-18 04:58 UTC, Chili-Man commented on Jenkinsfile
> +  OGContainer('devops', "${env.INTERNAL_REGISTRY_HOSTNAME}/devops", 'PR-18-2.3.0', [resourceLimitCpu: '2000m', resourceLimitMemory: '2Gi'])
2.3.0

2019-06-18 20:45 UTC, Chili-Man requested changes
Add a OG-CHANGELOG.md which specifies the changes we added to this

2019-06-18 20:45 UTC, Chili-Man commented on Jenkinsfile.properties
> +  regions: params['REGIONS'].split(','),
```suggestion
  regions: params['REGIONS'].split(',') as List,
```

2019-06-18 20:45 UTC, Chili-Man commented on Jenkinsfile.properties
> +    stringParam(name: 'AWS_ACCOUNT_CREDENTIAL_IDS', defaultValue: '', description: 'Comma separated Jenkins credential IDs for AWS accounts. Acceptable values are: development-aws,integration-aws,sta
mention that if its empty, then defaults will be used depending on if its a merge or a pull request

2019-06-18 20:45 UTC, Chili-Man commented on install-worker.sh
> +        set -x
remove

2019-06-18 20:45 UTC, Chili-Man commented on install-worker.sh
> +        set +x
remove

2019-06-18 20:45 UTC, Chili-Man commented on Jenkinsfile
> +
remove line

2019-06-18 20:45 UTC, Chili-Man commented on Jenkinsfile
> +                  sh "make VERSION=${KUBERNETES_VERSION} k8s"
only wrap this statement in the container('devops')

2019-06-18 23:40 UTC, sakomws commented on install-worker.sh
> +        set +x
ok

2019-06-18 23:40 UTC, sakomws commented on install-worker.sh
> +        set -x
ok

2019-06-18 23:40 UTC, sakomws commented on Jenkinsfile.properties
> +  regions: params['REGIONS'].split(','),
ok

2019-06-18 23:40 UTC, sakomws commented on Jenkinsfile.properties
> +    stringParam(name: 'AWS_ACCOUNT_CREDENTIAL_IDS', defaultValue: '', description: 'Comma separated Jenkins credential IDs for AWS accounts. Acceptable values are: development-aws,integration-aws,sta
ok

2019-06-19 00:26 UTC, Chili-Man submitted a review, later dismissed

2019-06-19 00:32 UTC, Chili-Man requested changes
Tagging did not working

2019-06-19 01:34 UTC, Chili-Man requested changes

2019-06-19 01:34 UTC, Chili-Man commented on Jenkinsfile
> +                  sh "make VERSION=${KUBERNETES_VERSION} k8s"
```suggestion
                 withEnv() {
                  sh "make VERSION=${KUBERNETES_VERSION} k8s"
                  }
```

2019-06-19 01:34 UTC, Chili-Man commented on Makefile
> +		-var ami_regions=$(ami_regions) \
capitalize

2019-06-19 01:34 UTC, Chili-Man commented on Jenkinsfile.properties
> +  regions: params['REGIONS'].split(',') as List,
dont
```suggestion
  regions: params['REGIONS'],
```

2019-06-19 02:08 UTC, Chili-Man requested changes

2019-06-19 02:08 UTC, Chili-Man commented on Jenkinsfile
> +                  withEnv(["REGIONS=${AMI_REGIONS}"]) {
```suggestion
                  withEnv(["AMI_REGIONS=${config.regions}"]) {
```

2019-06-19 02:08 UTC, Chili-Man commented on Jenkinsfile.properties
> +  regions: params['REGIONS'].split(','),
```suggestion
  regions: params['REGIONS'],
```

2019-06-19 03:19 UTC, Chili-Man approved these changes

2019-06-19 03:23 UTC, jspiro commented on Jenkinsfile
> +            echo "Would have ran: 'make VERSION=${KUBERNETES_VERSION} k8s'"
Declaring that I find this line BS and am approving under duress.

2019-06-19 03:23 UTC, jspiro approved these changes

2019-06-19 03:24 UTC, merged